## We first create own exception class names as OwnException which extends exception 
## And create another exception class as TestException

When we try to divide by zero it throws the exception which helps program to run after the error .
